export const glossary: Record<string, string> = {
  'Operating system':
    'System software that manages computer resources and provides an interface for system interaction.',
  Abstraction: 'A model of a complex system that includes only the details essential to the viewer.',
  Variable: 'A location in memory, referenced by an identifier, that contains a data value.',
  Constant: 'A value that cannot be changed during program execution.',
  Wireless: 'A network connection made without physical wires.',
  Stakeholders: 'People who have an interest in the outcome of a project.',
  'Dynamic data structure': 'A data structure that can grow and shrink in size during execution of a program.',
  Peripherals: 'Devices connected to a computer system outside of the core computer architecture.',
  Concurrently: 'Two or more tasks that are performed at the same time.',
  'Sub-program': 'A program that is called by another program.',
  Compression: 'A process that reduces the size of a file.',
  Patches: 'Updates to software that fix bugs or security issues.',
  Hexadecimal: 'A number system with a base of 16.',
  Recursor: 'The induction principle over an inductively-defined structure.',
  Dedicated: 'A computer system that is designed for a specific purpose.',
  'Fibre optic': 'A method of transmitting data using light.',
  Denary: 'A number system with a base of 10.',
  Network: 'A group of computers connected together.',
  Implementation: 'The process of switching to a new computer system within an organisation.',
};
