variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  before_script:
    - virtualenv env
    - . env/bin/activate
    - (cd client && npm install)
    - (cd server && pip install -r requirements.txt)
  cache:
    paths:
      - env/
      - .cache/pip/

build_job:
  stage: build
  script:
    - (cd client && npm run build)
    - (cd server && ./build.sh)

test_job:
  stage: test
  script:
    - (cd client && npm run build)
    - (cd server && ./build.sh && python3 manage.py test)

deploy_job:
  stage: deploy
  script:
    - (cd client && npm run build)
    - (cd server && ./build.sh && ./run.sh)
  environment: production
