# Generated by Django 4.2.1 on 2023-06-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='superuser',
            new_name='admin',
        ),
    ]
