# Generated by Django 4.2.1 on 2023-06-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_submission_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='publish_date',
            new_name='date',
        ),
    ]
