# Generated by Django 4.2.1 on 2023-06-09 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
  dependencies = [
    ("main", "0005_question_mark_minimum"),
  ]

  operations = [
    migrations.CreateModel(
      name="Chapter",
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
      ],
    ),
  ]
