# Generated by Django 4.2.1 on 2023-06-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_question_mark_minimum'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='resources',
            field=models.TextField(blank=True),
        ),
    ]
