# Generated by Django 4.2.1 on 2023-06-09 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
  dependencies = [
    ("main", "0006_CREATE_FAKE"),
  ]

  operations = [
    migrations.DeleteModel(
      name="Chapter",
    ),
  ]
