# Generated by Django 4.2.1 on 2023-06-09 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_chapter_topic_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="resources",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
