# Generated by Django 4.2.1 on 2023-06-16 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_attempt_begin_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='author',
            new_name='user',
        ),
    ]
