# Generated by Django 4.2.1 on 2023-06-17 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_submission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='time_limit',
        ),
        migrations.RemoveField(
            model_name='attemptsubmission',
            name='index',
        ),
        migrations.AlterField(
            model_name='attempt',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='main.sheet'),
        ),
    ]
