# Generated by Django 4.2.1 on 2023-06-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_attempt_time_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='time_limit',
            field=models.IntegerField(),
        ),
    ]
