# Generated by Django 4.2.1 on 2023-06-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_sheet_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='gpt_marking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_answer',
            field=models.TextField(),
        ),
    ]
