# Generated by Django 4.2.1 on 2023-06-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_submission_gpt_marking_alter_submission_user_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='begin_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
