# Generated by Django 4.2.1 on 2023-06-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mark_denominator',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='mark_maximum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
