# Generated by Django 4.2.1 on 2023-06-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_question_mark_denominator_question_mark_maximum'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mark_minimum',
            field=models.IntegerField(default=0),
        ),
    ]
